name: Update Configs and Stats

on:
  push:
    # Ø§ÛŒÙ† Ú¯Ø±Ø¯Ø´ Ú©Ø§Ø± Ø±ÙˆÛŒ Ù‡Ø± Ø´Ø§Ø®Ù‡â€ŒØ§ÛŒ Ú©Ù‡ Ø¨Ù‡ Ø¢Ù† Ù¾ÙˆØ´ Ø´ÙˆØ¯ Ø§Ø¬Ø±Ø§ Ù…ÛŒâ€ŒØ´ÙˆØ¯
    # Ø´Ù…Ø§ Ù…ÛŒâ€ŒØªÙˆØ§Ù†ÛŒØ¯ Ø¢Ù† Ø±Ø§ Ø¨Ù‡ Ø´Ø§Ø®Ù‡â€ŒÙ‡Ø§ÛŒ Ø®Ø§ØµÛŒ Ù…Ø­Ø¯ÙˆØ¯ Ú©Ù†ÛŒØ¯ØŒ Ù…Ø«Ù„Ø§Ù‹: branches: [ main, speed ]
    branches-ignore: []
  schedule:
    # Ø§ÛŒÙ† Ø¨Ø®Ø´ ÙÙ‚Ø· Ø±ÙˆÛŒ Ø´Ø§Ø®Ù‡ Ù¾ÛŒØ´â€ŒÙØ±Ø¶ (main) Ø§Ø¬Ø±Ø§ Ù…ÛŒâ€ŒØ´ÙˆØ¯
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script to generate files
        run: python categorize_all_protocols.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Ø¨Ø±Ø±Ø³ÛŒ ÙˆØ¬ÙˆØ¯ ØªØºÛŒÛŒØ±Ø§Øª
          if ! git diff-index --quiet HEAD; then
            echo "Changes found. Committing and pushing..."
            git add .
            git commit -m "ğŸ“Š Update configs and stats"
            
            # Ø¯Ø±ÛŒØ§ÙØª Ù†Ø§Ù… Ø´Ø§Ø®Ù‡ ÙØ¹Ù„ÛŒ Ùˆ Ù¾ÙˆØ´ Ø¨Ù‡ Ù‡Ù…Ø§Ù† Ø´Ø§Ø®Ù‡
            # GITHUB_REF_NAME Ø­Ø§ÙˆÛŒ Ù†Ø§Ù… Ø´Ø§Ø®Ù‡â€ŒØ§ÛŒ Ø§Ø³Øª Ú©Ù‡ Ú¯Ø±Ø¯Ø´ Ú©Ø§Ø± Ø±Ø§ ÙØ¹Ø§Ù„ Ú©Ø±Ø¯Ù‡
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit."
          fi
